// T0/T1-1: audio device list per JUCE WASAPI device type (spec Phase 0 (a)).
//
//   p0_devices            list only: never calls AudioIODevice::open(), so no stream is started and
//                         nothing is played. createDevice() activates a temporary IAudioClient per
//                         endpoint to query formats/periods (WASAPIDeviceBase constructor), which
//                         does not initialise or start a stream.
//   p0_devices --open     additionally opens each input alone and each output alone in the two
//                         shared modes (never exclusive), writes silence, reads the reported
//                         latencies, and closes. Not run during Phase 0 (no device is opened).
//
// Writes results/01-devices-list.csv and results/01-devices-list.txt.

#include "p0_common.h"

#include <juce_audio_devices/juce_audio_devices.h>

#include <cstdio>

using namespace p0;

namespace
{
struct Silence final : juce::AudioIODeviceCallback
{
    void audioDeviceIOCallbackWithContext (const float* const*, int, float* const* out, int numOut, int n,
                                           const juce::AudioIODeviceCallbackContext&) override
    {
        for (int c = 0; c < numOut; ++c) juce::FloatVectorOperations::clear (out[c], n);
    }
    void audioDeviceAboutToStart (juce::AudioIODevice*) override {}
    void audioDeviceStopped() override {}
};

juce::String joinD (const juce::Array<double>& a)
{
    juce::StringArray s;
    for (auto v : a) s.add (juce::String (v, 0));
    return s.joinIntoString (" ");
}
juce::String joinI (const juce::Array<int>& a)
{
    juce::StringArray s;
    for (auto v : a) s.add (juce::String (v));
    return s.joinIntoString (" ");
}
} // namespace

int main (int argc, char** argv)
{
    juce::ScopedJuceInitialiser_GUI juceInit;   // message manager only (hidden message window, nothing shown)
    Args args (argc, argv);
    const bool open = args.has ("--open");

    juce::String csv = "type,direction,device,sample_rates,buffer_sizes,default_buffer,reported_in_latency_samples,reported_out_latency_samples,opened_buffer,opened_rate,note\n";
    juce::String txt;
    txt << "# generated by p0_devices " << args.commandLine << "\n# date " << timestamp() << ", JUCE " << juce::SystemStats::getJUCEVersion()
        << ", open=" << (open ? "yes (shared modes only)" : "no (list only)") << "\n";

    juce::AudioDeviceManager dm;
    juce::OwnedArray<juce::AudioIODeviceType> types;
    dm.createAudioDeviceTypes (types);
    for (auto* type : types)
    {
        type->scanForDevices();
        const auto typeName = type->getTypeName();
        const bool exclusive = typeName.containsIgnoreCase ("Exclusive");
        txt << "\n## " << typeName << "\n";
        for (bool isInput : { true, false })
        {
            const auto names = type->getDeviceNames (isInput);
            const int def = type->getDefaultDeviceIndex (isInput);
            txt << (isInput ? "inputs" : "outputs") << " (" << names.size() << ", default index " << def << ")\n";
            for (const auto& name : names)
            {
                std::unique_ptr<juce::AudioIODevice> dev (isInput ? type->createDevice ({}, name) : type->createDevice (name, {}));
                juce::String rates, sizes, note;
                int defBuf = 0, inLat = -1, outLat = -1, openedBuf = 0;
                double openedRate = 0;
                if (dev != nullptr)
                {
                    rates = joinD (dev->getAvailableSampleRates());
                    sizes = joinI (dev->getAvailableBufferSizes());
                    defBuf = dev->getDefaultBufferSize();
                    if (open && ! exclusive)
                    {
                        juce::BigInteger ch;
                        ch.setRange (0, 2, true);
                        Silence cb;
                        auto err = isInput ? dev->open (ch, {}, 48000.0, 480) : dev->open ({}, ch, 48000.0, 480);
                        if (err.isEmpty())
                        {
                            dev->start (&cb);
                            juce::Thread::sleep (200);
                            inLat = dev->getInputLatencyInSamples();
                            outLat = dev->getOutputLatencyInSamples();
                            openedBuf = dev->getCurrentBufferSizeSamples();
                            openedRate = dev->getCurrentSampleRate();
                            dev->stop();
                            dev->close();
                        }
                        else
                        {
                            note = "open failed: " + err;
                        }
                    }
                    else
                    {
                        note = exclusive && open ? "exclusive: not opened" : "not opened (latency is reported only after open)";
                    }
                }
                else
                {
                    note = "createDevice failed";
                }
                csv << "\"" << typeName << "\"," << (isInput ? "in" : "out") << ",\"" << name.replace ("\"", "'") << "\",\"" << rates << "\",\"" << sizes << "\","
                    << defBuf << "," << (inLat >= 0 ? juce::String (inLat) : juce::String()) << "," << (outLat >= 0 ? juce::String (outLat) : juce::String()) << ","
                    << (openedBuf > 0 ? juce::String (openedBuf) : juce::String()) << "," << (openedRate > 0 ? juce::String (openedRate, 0) : juce::String()) << ",\"" << note << "\"\n";
                txt << "  - " << name << " | rates " << rates << " | buffers " << sizes << " | default " << defBuf
                    << (inLat >= 0 ? " | in latency " + juce::String (inLat) : juce::String())
                    << (outLat >= 0 ? " | out latency " + juce::String (outLat) : juce::String()) << " | " << note << "\n";
            }
        }
    }
    const bool cable = txt.contains ("CABLE Input") && txt.contains ("CABLE Output");
    txt << "\nVB-CABLE (\"CABLE Input\" and \"CABLE Output\") present: " << (cable ? "yes" : "no") << "\n";
    writeText (resultsDir().getChildFile ("01-devices-list.csv"), csv);
    writeText (resultsDir().getChildFile ("01-devices-list.txt"), txt);
    std::printf ("%s", txt.toRawUTF8());
    return 0;
}
